name: Python Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'  # Adjust the Python version as required

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pandas  # Install the necessary libraries
        pip install pytest  # Install pytest for testing

    - name: Run tests
      run: |
        # Assuming you have a test file, or you can add one later.
        # You might need to modify the paths or test cases as required
        pytest src/csv_app.py # Run tests with pytest (if you have any tests)

    - name: Check if the app runs without errors
      run: |
        # Run the script to ensure there are no runtime errors during execution
        python path_to_your_script.py  # Adjust path accordingly
